/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parkingsystem;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author abcd
 */
public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        changePasswordDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        changePasswordBtn = new javax.swing.JButton();
        clearParkedBtn = new javax.swing.JButton();
        clearAllLogsBtn = new javax.swing.JButton();
        systemInfoBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        changePasswordDialog.setTitle("Change Password");

        javax.swing.GroupLayout changePasswordDialogLayout = new javax.swing.GroupLayout(changePasswordDialog.getContentPane());
        changePasswordDialog.getContentPane().setLayout(changePasswordDialogLayout);
        changePasswordDialogLayout.setHorizontalGroup(
            changePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        changePasswordDialogLayout.setVerticalGroup(
            changePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PARKING SYSTEM");

        changePasswordBtn.setText("Change Password");
        changePasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordBtnActionPerformed(evt);
            }
        });

        clearParkedBtn.setText("Clear Parked");
        clearParkedBtn.setMaximumSize(new java.awt.Dimension(119, 23));
        clearParkedBtn.setMinimumSize(new java.awt.Dimension(119, 23));
        clearParkedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearParkedBtnActionPerformed(evt);
            }
        });

        clearAllLogsBtn.setText("Clear All Logs");
        clearAllLogsBtn.setMaximumSize(new java.awt.Dimension(119, 23));
        clearAllLogsBtn.setMinimumSize(new java.awt.Dimension(119, 23));
        clearAllLogsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllLogsBtnActionPerformed(evt);
            }
        });

        systemInfoBtn.setText("System Info");
        systemInfoBtn.setMaximumSize(new java.awt.Dimension(119, 23));
        systemInfoBtn.setMinimumSize(new java.awt.Dimension(119, 23));
        systemInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                systemInfoBtnActionPerformed(evt);
            }
        });

        backBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\abcd\\All In One\\All In One\\Work\\Me\\Class shit\\2nd Year\\1st Semester\\Object-Oriented Programming\\Netbeans Projects\\Parking System\\files\\otherImages\\back.png")); // NOI18N
        backBtn.setToolTipText("Back");
        backBtn.setPreferredSize(new java.awt.Dimension(25, 25));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(clearAllLogsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(changePasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(43, 43, 43)
                            .addComponent(clearParkedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(systemInfoBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(changePasswordBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(clearParkedBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(systemInfoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(clearAllLogsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearParkedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearParkedBtnActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Are You Sure You Want To Remove All Parked Rides?") == 0) {
            try {
                FileSystem.clearParked();
            } catch (Exception ex) {
                Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "All Rides Have Been Successfully removed!");
        }
    }//GEN-LAST:event_clearParkedBtnActionPerformed

    private void clearAllLogsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllLogsBtnActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Are You Sure You Want To Clear All Logs?") == 0) {
            try {
                FileSystem.clearAllLogs();
            } catch (Exception ex) {
                Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "All Logs Have Been Successfully cleared!");
        }
    }//GEN-LAST:event_clearAllLogsBtnActionPerformed

    private void changePasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordBtnActionPerformed
        try {
            Password.changePassword(this);
        } catch (Exception ex) {
            Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_changePasswordBtnActionPerformed

    private void systemInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systemInfoBtnActionPerformed
        JOptionPane.showMessageDialog(this, "Parking System is a simple and friendly system designed by:"
                        + "\n"
                        + "\nDagnachew Tesfaye"
                        + "\nDaniel Zelalem"
                        + "\nHena Fufa"
                        + "\nKalkidan Mesfin and"
                        + "\nLeykun Yilma"
                        + "\n"
                        + "\nThis system was designed using the programming language Java"
                        + "\nin the form of a real-world application for buildings that offer parking services."
                        + "\nPlease note that it was designed for use by administrators and not users.");
    }//GEN-LAST:event_systemInfoBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        ParkingSystem.switchFrame(this, new ParkingSystemFrame());
    }//GEN-LAST:event_backBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton changePasswordBtn;
    private javax.swing.JDialog changePasswordDialog;
    private javax.swing.JButton clearAllLogsBtn;
    private javax.swing.JButton clearParkedBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JButton systemInfoBtn;
    // End of variables declaration//GEN-END:variables
}
