/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parkingsystem;

import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author abcd
 */
public class UnparkFrame extends javax.swing.JFrame {
    String category = "";
    /**
     * Creates new form UnparkFrame
     */
    public UnparkFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rideableBtnGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        bicycleRadioBtn = new javax.swing.JRadioButton();
        motorcycleRadioBtn = new javax.swing.JRadioButton();
        smallCarRadioBtn = new javax.swing.JRadioButton();
        largeCarRadioBtn = new javax.swing.JRadioButton();
        plateNumberTextField = new javax.swing.JTextField();
        plateNumberLbl = new javax.swing.JLabel();
        unparkBtn = new javax.swing.JButton();
        errorMessageLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        pictureLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PARKING SYSTEM");

        rideableBtnGroup.add(bicycleRadioBtn);
        bicycleRadioBtn.setText("Bicycle");
        bicycleRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bicycleRadioBtnActionPerformed(evt);
            }
        });

        rideableBtnGroup.add(motorcycleRadioBtn);
        motorcycleRadioBtn.setText("Motorcycle");
        motorcycleRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motorcycleRadioBtnActionPerformed(evt);
            }
        });

        rideableBtnGroup.add(smallCarRadioBtn);
        smallCarRadioBtn.setText("Small Car");
        smallCarRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallCarRadioBtnActionPerformed(evt);
            }
        });

        rideableBtnGroup.add(largeCarRadioBtn);
        largeCarRadioBtn.setText("Large Car");
        largeCarRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largeCarRadioBtnActionPerformed(evt);
            }
        });

        plateNumberTextField.setEditable(false);
        plateNumberTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        plateNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plateNumberTextFieldActionPerformed(evt);
            }
        });
        plateNumberTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                plateNumberTextFieldKeyReleased(evt);
            }
        });

        plateNumberLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        plateNumberLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        plateNumberLbl.setText("Plate Number");

        unparkBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        unparkBtn.setForeground(new java.awt.Color(0, 204, 204));
        unparkBtn.setText("UNPARK");
        unparkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unparkBtnActionPerformed(evt);
            }
        });

        errorMessageLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        errorMessageLbl.setForeground(new java.awt.Color(255, 0, 0));
        errorMessageLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        backBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\abcd\\All In One\\All In One\\Work\\Me\\Class shit\\2nd Year\\1st Semester\\Object-Oriented Programming\\Netbeans Projects\\Parking System\\files\\otherImages\\back.png")); // NOI18N
        backBtn.setToolTipText("Back");
        backBtn.setPreferredSize(new java.awt.Dimension(25, 25));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jInternalFrame1.setAutoscrolls(true);
        jInternalFrame1.setVisible(true);

        pictureLbl.setIcon(new javax.swing.ImageIcon("C:\\Users\\abcd\\All In One\\All In One\\Work\\Me\\Class shit\\2nd Year\\1st Semester\\Object-Oriented Programming\\Netbeans Projects\\Parking System\\files\\otherImages\\default.jpg")); // NOI18N

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pictureLbl)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pictureLbl)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bicycleRadioBtn)
                                .addGap(2, 2, 2)
                                .addComponent(motorcycleRadioBtn)
                                .addGap(2, 2, 2)
                                .addComponent(smallCarRadioBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(largeCarRadioBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(plateNumberLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(plateNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(55, 55, 55)
                                                .addComponent(unparkBtn))
                                            .addComponent(errorMessageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bicycleRadioBtn)
                    .addComponent(motorcycleRadioBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(smallCarRadioBtn)
                        .addComponent(largeCarRadioBtn)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plateNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plateNumberLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorMessageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unparkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bicycleRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bicycleRadioBtnActionPerformed
        plateNumberLbl.setText("Full Name");
        plateNumberTextField.setEditable(true);
        category = "bicycle";
    }//GEN-LAST:event_bicycleRadioBtnActionPerformed

    private void motorcycleRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motorcycleRadioBtnActionPerformed
        plateNumberLbl.setText("Plate Number");
        plateNumberTextField.setEditable(true);
        category = "motorcycle";
    }//GEN-LAST:event_motorcycleRadioBtnActionPerformed

    private void smallCarRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallCarRadioBtnActionPerformed
        plateNumberLbl.setText("Plate Number");
        plateNumberTextField.setEditable(true);
        category = "smallcar";
    }//GEN-LAST:event_smallCarRadioBtnActionPerformed

    private void largeCarRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largeCarRadioBtnActionPerformed
        plateNumberLbl.setText("Plate Number");
        plateNumberTextField.setEditable(true);
        category = "largecar";
    }//GEN-LAST:event_largeCarRadioBtnActionPerformed

    private void plateNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plateNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plateNumberTextFieldActionPerformed

    private void unparkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unparkBtnActionPerformed
        if (verify()) {
            String plateNo = plateNumberTextField.getText();
            try {
                double cost = ParkingSystem.unpark(plateNo, category, this);
                if (cost != 0) {
                    double cost2 = Math.round(cost * 100)/100.0;
                    pictureLbl.setIcon(new javax.swing.ImageIcon("files\\otherImages\\default.jpg"));
                    JOptionPane.showMessageDialog(this, "Your ride has been successfully unparked."
                            + "\nPlease pay birr " + String.valueOf(cost2) + " and take your ride!");
                    File f = new File("files\\parkedRideImages\\" + plateNo + ".jpg");
                    f.delete();
                    ParkingSystem.switchFrame(this, new ParkingSystemFrame());
                }
            } catch (Exception ex) {
                Logger.getLogger(UnparkFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_unparkBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        try {
            ParkingSystem.switchFrame(this, new ParkingSystemFrame());
        }
        catch (Exception e) {}
    }//GEN-LAST:event_backBtnActionPerformed

    private void plateNumberTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_plateNumberTextFieldKeyReleased
        if (evt.getKeyCode() == 10) {
            String f = "files\\parkedRideImages\\" + plateNumberTextField.getText() + ".jpg";
            pictureLbl.setIcon(new javax.swing.ImageIcon(f));
        }
    }//GEN-LAST:event_plateNumberTextFieldKeyReleased

    private boolean verify() {
        String errorMsg = "";
        if (plateNumberTextField.getText().isEmpty()) {
            errorMsg = "Must enter plate number!";
        }
        errorMessageLbl.setText(errorMsg);
        return errorMsg.equals("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JRadioButton bicycleRadioBtn;
    private javax.swing.JLabel errorMessageLbl;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton largeCarRadioBtn;
    private javax.swing.JRadioButton motorcycleRadioBtn;
    private javax.swing.JLabel pictureLbl;
    private javax.swing.JLabel plateNumberLbl;
    private javax.swing.JTextField plateNumberTextField;
    private javax.swing.ButtonGroup rideableBtnGroup;
    private javax.swing.JRadioButton smallCarRadioBtn;
    private javax.swing.JButton unparkBtn;
    // End of variables declaration//GEN-END:variables
}
